"use client";

import { useEffect, useMemo, useState } from "react";
import WorkspacePanel from "./WorkspacePanel";
import ContractRoutesPanel from "./ContractRoutesPanel";
import { Briefcase, FileStack, FileText, Folder, LayoutDashboard, Lock, LogOut, Search, Settings, ShieldCheck, Star, User } from "lucide-react";

const TIERS = [["estrategico","Procesos Estratégicos"],["misional","Procesos Misionales"],["apoyo","Procesos de Apoyo"],["evaluacion","Procesos de Evaluación"]];
const STATES = { vigente:"Vigente", no_publicado:"No publicado", obsoleto:"Obsoleto", anulado:"Anulado" };

export default function DashboardApp(){
  const [loaded,setLoaded]=useState(false),[user,setUser]=useState(null),[active,setActive]=useState("consulta"),[mapMode,setMapMode]=useState("cards"),[processes,setProcesses]=useState([]),[docTypes,setDocTypes]=useState([]),[docs,setDocs]=useState([]),[q,setQ]=useState(""),[selectedProcess,setSelectedProcess]=useState(null),[detail,setDetail]=useState(null);
  const isAdmin=user?.isAdmin===true;
  async function loadAll(){const[p,t,d]=await Promise.all([fetch("/api/processes",{cache:"no-store"}).then(r=>r.json()),fetch("/api/doctypes",{cache:"no-store"}).then(r=>r.json()),fetch("/api/documents",{cache:"no-store"}).then(r=>r.json())]);setProcesses(Array.isArray(p)?p:[]);setDocTypes(Array.isArray(t)?t:[]);setDocs(Array.isArray(d)?d.map(x=>({...x,processId:x.process_id,typeId:x.type_id,hasFile:!!x.has_file,file:x.file_name})):[])}
  useEffect(()=>{(async()=>{const me=await fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()).catch(()=>null);setUser(me||null);if(me)await loadAll();setLoaded(true)})()},[]);
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setUser(null)}
  const procById=id=>processes.find(p=>p.id===id), typeById=id=>docTypes.find(t=>t.id===id), countFor=pid=>docs.filter(d=>d.processId===pid&&d.state==="vigente").length;
  const filteredDocs=useMemo(()=>{const term=q.trim().toLowerCase();return docs.filter(d=>{if(selectedProcess&&d.processId!==selectedProcess.id)return false;if(!term)return true;const p=procById(d.processId),t=typeById(d.typeId);return[d.name,d.code,d.file,p?.name,p?.sigla,t?.name,t?.sigla].filter(Boolean).some(x=>String(x).toLowerCase().includes(term))})},[docs,q,selectedProcess,processes,docTypes]);
  if(!loaded)return <div className="loading">Cargando plataforma…</div>;
  if(!user)return <AuthScreen onLogin={async()=>{const me=await fetch("/api/auth/me").then(r=>r.json());setUser(me);await loadAll()}}/>;
  return <div className="shell"><aside className="sidebar"><div className="side-brand"><img src="/branding/logo-grupo-ingenio.png" alt="Grupo Ingenio" onError={e=>{e.currentTarget.style.display="none"}}/><div><h1>Grupo Ingenio</h1><p>Gestión documental</p></div></div><nav className="side-nav"><button className={active==="consulta"?"active":""} onClick={()=>{setActive("consulta");setSelectedProcess(null)}}><LayoutDashboard size={17}/> Consulta documental</button><button className={active==="workspace"?"active":""} onClick={()=>setActive("workspace")}><Star size={17}/> Mi espacio / Plan</button><button className={active==="contracts"?"active":""} onClick={()=>setActive("contracts")}><Briefcase size={17}/> Contratos / Rutas</button>{isAdmin&&<button className={active==="admin"?"active":""} onClick={()=>setActive("admin")}><Settings size={17}/> Administración</button>}</nav><div className="side-block"><span className="side-label">Módulos activos</span><div className="soon"><FileStack size={15}/> Repositorio</div><div className="soon"><Folder size={15}/> Plan personal</div><div className="soon"><Briefcase size={15}/> Rutas contractuales</div></div><div className="user-card"><div className="avatar">{user.full_name?.[0]||"U"}</div><div className="user-meta"><strong>{user.full_name}</strong><span>{user.cargo||"Usuario"}</span>{isAdmin&&<em><ShieldCheck size={13}/> Admin</em>}</div></div></aside><main className="main"><header className="topbar"><div className="top-title"><span className="eyebrow mini">Grupo Ingenio</span><strong>{active==="contracts"?"Contratos / Rutas de trabajo":active==="workspace"?"Mi espacio de trabajo":active==="admin"?"Panel de administración":"Consulta inteligente"}</strong></div><div className="top-actions"><button className="chip-btn"><User size={15}/> Perfil</button><button className="chip-btn danger-lite" onClick={logout}><LogOut size={15}/> Salir</button></div></header><div className="wrap dashboard-wrap">{active==="contracts"&&<ContractRoutesPanel user={user}/>} {active==="workspace"&&<WorkspacePanel docs={docs} procById={procById} typeById={typeById} setDetail={setDetail}/>} {active==="consulta"&&<ConsultaPanel mapMode={mapMode} setMapMode={setMapMode} processes={processes} docs={docs} q={q} setQ={setQ} selectedProcess={selectedProcess} setSelectedProcess={setSelectedProcess} filteredDocs={filteredDocs} procById={procById} typeById={typeById} countFor={countFor} setDetail={setDetail}/>} {active==="admin"&&isAdmin&&<AdminPanel docs={docs} procById={procById} typeById={typeById}/>}</div></main>{detail&&<DocumentViewer doc={detail} procById={procById} typeById={typeById} onClose={()=>setDetail(null)}/>}</div>;
}

function ConsultaPanel(p){return <section className="section dashboard-section"><div className="hero-panel"><div className="hero-copy"><div className="eyebrow">Gestión documental inteligente</div><h2>Consulta por procesos o búsqueda global</h2><p>Busca por código, nombre, proceso, tipo documental o palabra clave.</p></div><div className="searchbar hero-search"><Search size={18}/><input value={p.q} onChange={e=>p.setQ(e.target.value)} placeholder="Buscar documentos…"/></div><div className="stats-grid"><Stat label="Documentos" value={p.docs.length}/><Stat label="Procesos" value={p.processes.length}/><Stat label="Vigentes" value={p.docs.filter(d=>d.state==="vigente").length}/><Stat label="Resultado" value={p.filteredDocs.length}/></div></div><div className="section-title-row"><div><div className="eyebrow">Mapa de procesos</div><h2 className="h2">Navegación institucional</h2></div><div className="tabs"><button className={p.mapMode==="cards"?"on":""} onClick={()=>p.setMapMode("cards")}>Tarjetas</button><button className={p.mapMode==="image"?"on":""} onClick={()=>p.setMapMode("image")}>Mapa interactivo</button></div></div>{p.mapMode==="image"?<InteractiveMap processes={p.processes} setSelectedProcess={p.setSelectedProcess}/>:TIERS.map(([id,label])=><ProcessTier key={id} id={id} label={label} processes={p.processes} setSelectedProcess={p.setSelectedProcess} countFor={p.countFor}/>) }<div className="section-title-row"><div><div className="eyebrow">Documentos {p.selectedProcess?`· ${p.selectedProcess.name}`:""}</div><h2 className="h2">Resultados</h2></div>{p.selectedProcess&&<button className="btn btn-ghost" onClick={()=>p.setSelectedProcess(null)}>Ver todos</button>}</div><div className="doc-grid">{p.filteredDocs.map(d=><button key={d.id} className="doc-card" onClick={()=>p.setDetail(d)}><div className="doc-icon"><FileText size={20}/></div><span className="code">{d.code}</span><h4>{d.name}</h4><p>{p.procById(d.processId)?.name} · {p.typeById(d.typeId)?.name}</p><div className="doc-card-foot"><span>{STATES[d.state]||d.state}</span><span className="view-link">Ver</span></div></button>)}</div>{!p.filteredDocs.length&&<div className="empty-state"><h3>Sin documentos</h3><p>No hay coincidencias con los filtros actuales.</p></div>}</section>}
function ProcessTier({id,label,processes,setSelectedProcess,countFor}){const list=processes.filter(p=>p.tier===id);if(!list.length)return null;return <div className="tier"><div className="tier-head"><div className="tier-bar"/><h3>{label}</h3><span>· {list.length}</span></div><div className="grid process-grid">{list.map(p=><button className="pcard" key={p.id} onClick={()=>setSelectedProcess(p)}><span className="sig">{p.sigla}</span><h4>{p.name}</h4><div className="meta"><span className="count"><FileStack size={14}/> {countFor(p.id)} vigentes</span><span className="go">Abrir</span></div></button>)}</div></div>}
function InteractiveMap({processes,setSelectedProcess}){const byTier=tier=>processes.filter(p=>p.tier===tier);return <div className="interactive-map"><img src="/branding/mapa-procesos-grupo-ingenio.png" alt="Mapa de procesos"/><div className="map-layers">{TIERS.map(([id,label])=><div className="map-hotspot" key={id}><h3>{label}</h3>{byTier(id).map(p=><button key={p.id} onClick={()=>setSelectedProcess(p)}>{p.name}</button>)}</div>)}</div></div>}
function AdminPanel({docs,procById,typeById}){return <section className="section dashboard-section"><div className="admin-hero"><div><div className="eyebrow">Panel de administración</div><h2 className="h2">Gestión de documentos</h2><p className="lead">Vista administrativa de documentos cargados en el repositorio.</p></div></div><table className="table"><thead><tr><th>Código</th><th>Nombre</th><th>Proceso</th><th>Tipo</th><th>Estado</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><span className="code">{d.code}</span></td><td>{d.name}</td><td>{procById(d.processId)?.name}</td><td>{typeById(d.typeId)?.name}</td><td>{STATES[d.state]||d.state}</td></tr>)}</tbody></table></section>}
function DocumentViewer({doc,procById,typeById,onClose}){return <div className="overlay" onClick={onClose}><div className="contract-viewer" onClick={e=>e.stopPropagation()}><div className="viewer-head"><h3>{doc.name}</h3><button className="iconbtn" onClick={onClose}>×</button></div><div className="viewer-body"><aside className="viewer-info"><h4>Ficha técnica</h4><div><b>Código</b><span>{doc.code}</span></div><div><b>Proceso</b><span>{procById(doc.processId)?.name}</span></div><div><b>Tipo</b><span>{typeById(doc.typeId)?.name}</span></div><div><b>Estado</b><span>{STATES[doc.state]||doc.state}</span></div>{doc.hasFile&&<a className="btn btn-primary" href={`/api/documents/${doc.id}/file`} target="_blank">Abrir / descargar</a>}</aside><main className="viewer-preview">{doc.hasFile?<iframe src={`/api/documents/${doc.id}/file`} title={doc.name}/>:<div className="empty-state"><h3>Sin archivo</h3><p>Este documento no tiene archivo adjunto.</p></div>}</main></div></div></div>}
function Stat({label,value}){return <div className="stat-card"><strong>{value}</strong><span>{label}</span></div>}
function AuthScreen({onLogin}){const[tab,setTab]=useState("login"),[form,setForm]=useState({full_name:"",cedula:"",cargo:"",email:"",password:""}),[err,setErr]=useState("");async function submit(){setErr("");const url=tab==="login"?"/api/auth/login":"/api/auth/register";const body=tab==="login"?{email:form.email,password:form.password}:form;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)return setErr((await r.json()).error||"No fue posible continuar");if(tab==="register")return setTab("login");onLogin()}const set=(k,v)=>setForm({...form,[k]:v});return <div className="auth-shell"><div className="auth-visual"><img src="/branding/logo-grupo-ingenio.png" alt="Grupo Ingenio"/><h1>Repositorio Documental</h1><p>Consulta, contratos, evidencias y plan de trabajo en una sola plataforma.</p></div><div className="auth-card"><div className="tabs auth-tabs"><button className={tab==="login"?"on":""} onClick={()=>setTab("login")}>Iniciar sesión</button><button className={tab==="register"?"on":""} onClick={()=>setTab("register")}>Registrarse</button></div><div className="form-stack">{tab==="register"&&<><div className="field"><label>Nombre completo</label><input value={form.full_name} onChange={e=>set("full_name",e.target.value)}/></div><div className="row2"><div className="field"><label>Cédula</label><input value={form.cedula} onChange={e=>set("cedula",e.target.value)}/></div><div className="field"><label>Cargo</label><input value={form.cargo} onChange={e=>set("cargo",e.target.value)}/></div></div></>}<div className="field"><label>Correo</label><input value={form.email} onChange={e=>set("email",e.target.value)}/></div><div className="field"><label>Contraseña</label><input type="password" value={form.password} onChange={e=>set("password",e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()}/></div>{err&&<div className="err">{err}</div>}<button className="btn btn-primary" onClick={submit}><Lock size={15}/> {tab==="login"?"Entrar":"Crear cuenta"}</button></div></div></div>}
