"use client";
import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Briefcase, CheckCircle, ClipboardList, FileArchive, RefreshCw, XCircle } from "lucide-react";
const METRICS=[["active_contracts","Contratos activos",Briefcase],["expiring_contracts","Próximos a vencer",AlertTriangle],["pending_documents","Documentos pendientes",ClipboardList],["approved_documents","Documentos aprobados",CheckCircle],["rejected_documents","Documentos rechazados",XCircle],["activities","Actividades creadas",Activity],["pending_activities","Actividades por revisar",RefreshCw],["approved_activities","Actividades aprobadas",CheckCircle],["rejected_activities","Actividades rechazadas",XCircle],["internal_documents","Documentos internos",FileArchive]];
export default function ExecutiveDashboardPanel(){
 const[data,setData]=useState(null),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/dashboard/executive"),d=await r.json();if(!r.ok)setError(d.error);else setData(d)}
 useEffect(()=>{load()},[]);
 if(!data)return <div className="empty-state"><h3>{error||"Cargando tablero gerencial…"}</h3></div>;
 return <section className="executive-panel"><header><div><span className="eyebrow">Visión ejecutiva</span><h2>Tablero Gerencial</h2><p>Estado contractual, cumplimiento documental y actividad del equipo en una sola lectura.</p></div><button className="btn btn-ghost" onClick={load}><RefreshCw size={15}/> Actualizar</button></header><div className="executive-kpis">{METRICS.map(([key,title,Icon])=><article key={key}><Icon size={20}/><strong>{data.metrics[key]||0}</strong><span>{title}</span></article>)}</div><div className="executive-grid"><section><div className="section-title-row"><div><h3>Avance por contrato</h3><p>Contratos críticos y nivel de aprobación de actividades.</p></div></div>{data.contracts.map(c=>{const pct=c.total?Math.round(c.approved/c.total*100):0;return <article className="executive-contract" key={c.id}><div><b>{c.title}</b><small>{c.code||"Sin código"} · vence {String(c.end_date||"sin fecha").slice(0,10)}</small></div><strong>{pct}%</strong><i><em style={{width:`${pct}%`}}/></i></article>})}</section><section><div className="section-title-row"><div><h3>Usuarios con pendientes</h3><p>Concentración de entregas por atender.</p></div></div>{data.users.map(u=><article className="executive-user" key={u.id}><div className="avatar">{u.full_name?.[0]}</div><div><b>{u.full_name}</b><small>{u.cargo}</small></div><strong>{u.pending} pendientes</strong></article>)}</section><section className="wide"><div className="section-title-row"><div><h3>Actividades recientes</h3><p>Últimos movimientos de ejecución contractual.</p></div></div><div className="executive-recent">{data.recent.map(a=><article key={a.id}><Activity size={16}/><div><b>{a.title}</b><small>{a.user_name} · {a.contract_name}</small></div><span>{a.status}</span></article>)}</div></section></div></section>
}
