"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,ChevronRight,Download,Eye,FileArchive,FileText,Folder,FolderOpen,History,Move,PanelLeftClose,Pencil,Plus,Search,Trash2,UploadCloud,X} from "lucide-react";

async function api(url,options){const r=await fetch(url,{cache:"no-store",...options}),d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"No fue posible completar la acción");return d;}
const TYPES=["contrato","acta","informe","certificado","jurídico","financiero","talento humano","propuesta","otro"];
const fmt=n=>!n?"—":n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`;

export default function InternalDocumentationPanel(){
 const[folders,setFolders]=useState([]),[docs,setDocs]=useState([]),[events,setEvents]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(""),[type,setType]=useState(""),[modal,setModal]=useState(null),[detail,setDetail]=useState(null),[docEvents,setDocEvents]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const current=folders.find(f=>Number(f.id)===Number(selected));
 const children=folders.filter(f=>Number(f.parent_id||0)===Number(selected||0));
 const path=useMemo(()=>{const out=[];let f=current;while(f){out.unshift(f);f=folders.find(x=>Number(x.id)===Number(f.parent_id));}return out},[current,folders]);
 async function loadFolders(){setFolders(await api("/api/internal-docs/folders"))}
 async function loadContent(){const id=selected||"root";const[d,e]=await Promise.all([api(`/api/internal-docs/documents?folderId=${id}&q=${encodeURIComponent(query)}&type=${encodeURIComponent(type)}`),api(`/api/internal-docs/events${selected?`?folderId=${selected}`:""}`)]);setDocs(d);setEvents(e)}
 useEffect(()=>{loadFolders().catch(e=>setError(e.message))},[]);useEffect(()=>{const t=setTimeout(()=>loadContent().catch(e=>setError(e.message)),180);return()=>clearTimeout(t)},[selected,query,type]);
 async function refresh(){await Promise.all([loadFolders(),loadContent()])}
 async function saveFolder(){setBusy(true);try{const editing=modal.folder;await api(editing?`/api/internal-docs/folders/${editing.id}`:"/api/internal-docs/folders",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?modal.form:{...modal.form,parent_id:selected})});setModal(null);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function upload(){const files=modal.form.files;if(!files?.length)return setError("Selecciona al menos un archivo");setBusy(true);try{const fd=new FormData();Object.entries(modal.form).forEach(([k,v])=>{if(k!=="files"&&v!=null)fd.set(k,v)});fd.set("folderId",selected||"");Array.from(files).forEach(f=>fd.append("files",f));await api("/api/internal-docs/documents",{method:"POST",body:fd});setModal(null);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveDocument(){setBusy(true);try{await api(`/api/internal-docs/documents/${modal.doc.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(modal.form)});setModal(null);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removeFolder(f){if(!confirm(`¿Eliminar la carpeta vacía “${f.name}”?`))return;try{await api(`/api/internal-docs/folders/${f.id}`,{method:"DELETE"});if(Number(selected)===Number(f.id))setSelected(f.parent_id||null);await refresh()}catch(e){setError(e.message)}}
 async function removeDoc(d){if(!confirm(`¿Eliminar “${d.title}”? Esta acción quedará registrada.`))return;try{await api(`/api/internal-docs/documents/${d.id}`,{method:"DELETE"});await refresh()}catch(e){setError(e.message)}}
 async function openDetail(d){setDetail(d);setDocEvents(await api(`/api/internal-docs/documents/${d.id}/events`).catch(()=>[]))}
 return <section className="internal-docs">
  <header className="internal-hero"><div><span className="eyebrow"><Archive size={15}/> Archivo administrativo</span><h2>Documentación Interna Grupo Ingenio</h2><p>Organiza, consulta y controla el archivo privado con trazabilidad completa.</p></div><div className="internal-hero-stats"><span><b>{folders.length}</b> carpetas</span><span><b>{docs.length}</b> documentos aquí</span><span><b>{events.length}</b> movimientos</span></div></header>
  {error&&<div className="error-banner">{error}<button onClick={()=>setError("")}>Cerrar</button></div>}
  <div className="internal-layout"><aside className="folder-pane"><div className="pane-heading"><div><small>ESTRUCTURA</small><h3>Carpetas</h3></div><button title="Nueva carpeta raíz" onClick={()=>{setSelected(null);setModal({type:"folder",form:{name:"",description:""}})}}><Plus size={17}/></button></div><button className={!selected?"tree-root on":"tree-root"} onClick={()=>setSelected(null)}><FolderOpen size={18}/><span>Documentación Interna<small>Raíz del archivo</small></span></button><FolderTree folders={folders} parent={null} selected={selected} onSelect={setSelected}/><div className="folder-pane-note"><History size={16}/><p>Cada carga, movimiento, edición y descarga queda registrada.</p></div></aside>
   <main className="folder-content"><div className="internal-breadcrumb"><button onClick={()=>setSelected(null)}>Documentación Interna</button>{path.map(f=><span key={f.id}><ChevronRight size={14}/><button onClick={()=>setSelected(f.id)}>{f.name}</button></span>)}</div>
    <div className="folder-content-head"><div><small>CARPETA ACTUAL</small><h2>{current?.name||"Archivo principal"}</h2><p>{current?.description||"Documentación administrativa reservada para el equipo administrador."}</p></div><div className="content-actions"><button className="btn btn-ghost" onClick={()=>setModal({type:"folder",form:{name:"",description:""}})}><Folder size={16}/> Nueva carpeta</button><button className="btn btn-primary" onClick={()=>setModal({type:"upload",form:{title:"",description:"",documentType:"otro",tags:"",status:"vigente",accessLevel:"admin_only",observations:"",files:null}})}><UploadCloud size={16}/> Subir documentos / ZIP</button>{current&&<><button className="icon-action" title="Renombrar carpeta" onClick={()=>setModal({type:"folder",folder:current,form:{name:current.name,description:current.description||""}})}><Pencil size={16}/></button><button className="icon-action danger" title="Eliminar carpeta" onClick={()=>removeFolder(current)}><Trash2 size={16}/></button></>}</div></div>
    <div className="internal-toolbar"><div className="searchbar"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en esta carpeta…"/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos los tipos</option>{TYPES.map(t=><option key={t}>{t}</option>)}</select></div>
    {!!children.length&&<section className="content-block"><div className="block-title"><h3>Carpetas</h3><span>{children.length} elementos</span></div><div className="internal-grid folders">{children.map(f=><article className="folder-card" key={f.id} onClick={()=>setSelected(f.id)}><div className="folder-icon"><Folder size={27}/></div><div><h4>{f.name}</h4><p>{f.description||"Subcarpeta interna"}</p><small>{f.subfolder_count} subcarpetas · {f.document_count} documentos</small></div><ChevronRight size={18}/></article>)}</div></section>}
    <section className="content-block"><div className="block-title"><h3>Documentos</h3><span>{docs.length} archivos</span></div><div className="internal-grid documents">{docs.map(d=><article className="internal-file" key={d.id}><div className="internal-file-top">{/zip|rar|archive/i.test(`${d.mime_type} ${d.original_file_name}`)?<FileArchive size={25}/>:<FileText size={25}/>}<span className={`doc-state ${d.status}`}>{d.status}</span></div><h4>{d.title}</h4><p>{d.original_file_name}</p><div className="file-tags"><span>{d.document_type||"otro"}</span>{d.tags&&<span>{d.tags.split(",")[0]}</span>}</div><small>{fmt(d.size_bytes)} · {d.uploaded_by_name}<br/>{d.created_at_formatted}</small><div className="file-actions"><button onClick={()=>openDetail(d)}><Eye size={15}/> Detalle</button><a href={`/api/internal-docs/documents/${d.id}/file`} target="_blank"><Download size={15}/></a><button title="Editar o mover" onClick={()=>setModal({type:"document",doc:d,form:{folder_id:d.folder_id,title:d.title,description:d.description||"",document_type:d.document_type||"otro",tags:d.tags||"",status:d.status,access_level:d.access_level,observations:d.observations||""}})}><Move size={15}/></button><button className="danger" onClick={()=>removeDoc(d)}><Trash2 size={15}/></button></div></article>)}</div>{!docs.length&&!children.length&&<div className="internal-empty"><UploadCloud size={38}/><h3>Esta carpeta está lista para recibir documentos</h3><p>Crea una subcarpeta o carga archivos individuales, múltiples archivos y paquetes ZIP.</p><button className="btn btn-primary" onClick={()=>setModal({type:"upload",form:{documentType:"otro",status:"vigente",accessLevel:"admin_only"}})}>Subir primeros archivos</button></div>}</section>
    <section className="folder-history"><div className="block-title"><h3>Actividad reciente</h3><span>Trazabilidad</span></div><div>{events.slice(0,8).map(e=><article key={e.id}><i><History size={15}/></i><p><b>{e.description}</b><span>{e.actor_name||"Sistema"} · {e.created_at_formatted}</span></p></article>)}</div></section>
   </main></div>
  {modal?.type==="folder"&&<Modal title={modal.folder?"Editar carpeta":"Nueva carpeta"} subtitle={modal.folder?"Actualiza su identificación":"Se creará dentro de la ubicación que estás viendo"} busy={busy} onClose={()=>setModal(null)} onSave={saveFolder}><Destination path={path}/><Field label="Nombre de la carpeta"><input autoFocus value={modal.form.name} onChange={e=>setModal({...modal,form:{...modal.form,name:e.target.value}})}/></Field><Field label="Descripción"><textarea value={modal.form.description} onChange={e=>setModal({...modal,form:{...modal.form,description:e.target.value}})}/></Field></Modal>}
  {modal?.type==="upload"&&<Modal wide title="Subir documentación interna" subtitle="Carga uno o varios archivos; los ZIP se conservan como paquetes descargables" busy={busy} onClose={()=>setModal(null)} onSave={upload}><Destination path={path}/><div className="form-grid"><Field label="Título (opcional para carga individual)"><input value={modal.form.title||""} onChange={e=>setModal({...modal,form:{...modal.form,title:e.target.value}})}/></Field><Field label="Tipo documental"><select value={modal.form.documentType||"otro"} onChange={e=>setModal({...modal,form:{...modal.form,documentType:e.target.value}})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Etiquetas"><input placeholder="legal, 2026, vigente" value={modal.form.tags||""} onChange={e=>setModal({...modal,form:{...modal.form,tags:e.target.value}})}/></Field><Field label="Estado"><select value={modal.form.status||"vigente"} onChange={e=>setModal({...modal,form:{...modal.form,status:e.target.value}})}>{["vigente","archivado","reemplazado"].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Descripción"><textarea value={modal.form.description||""} onChange={e=>setModal({...modal,form:{...modal.form,description:e.target.value}})}/></Field><label className="drop-zone"><UploadCloud size={30}/><b>Selecciona archivos o paquetes ZIP</b><span>PDF, Office, imágenes, ZIP, RAR y otros formatos</span><input type="file" multiple onChange={e=>setModal({...modal,form:{...modal.form,files:e.target.files}})}/><em>{modal.form.files?.length?`${modal.form.files.length} archivo(s) seleccionado(s)`:"Explorar archivos"}</em></label><Field label="Observaciones internas"><textarea value={modal.form.observations||""} onChange={e=>setModal({...modal,form:{...modal.form,observations:e.target.value}})}/></Field></Modal>}
  {modal?.type==="document"&&<Modal wide title="Editar o mover documento" subtitle="Los cambios quedarán registrados en la trazabilidad" busy={busy} onClose={()=>setModal(null)} onSave={saveDocument}><div className="form-grid"><Field label="Título"><input value={modal.form.title} onChange={e=>setModal({...modal,form:{...modal.form,title:e.target.value}})}/></Field><Field label="Carpeta destino"><select value={modal.form.folder_id||""} onChange={e=>setModal({...modal,form:{...modal.form,folder_id:e.target.value||null}})}><option value="">Raíz</option>{folders.map(f=><option key={f.id} value={f.id}>{folderLabel(f,folders)}</option>)}</select></Field><Field label="Tipo documental"><select value={modal.form.document_type} onChange={e=>setModal({...modal,form:{...modal.form,document_type:e.target.value}})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Estado"><select value={modal.form.status} onChange={e=>setModal({...modal,form:{...modal.form,status:e.target.value}})}>{["vigente","archivado","reemplazado"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Etiquetas"><input value={modal.form.tags} onChange={e=>setModal({...modal,form:{...modal.form,tags:e.target.value}})}/></Field><Field label="Acceso"><select value={modal.form.access_level} onChange={e=>setModal({...modal,form:{...modal.form,access_level:e.target.value}})}><option value="admin_only">Solo administradores</option><option value="specific_user">Admin y usuario específico (preparado)</option></select></Field></div><Field label="Descripción"><textarea value={modal.form.description} onChange={e=>setModal({...modal,form:{...modal.form,description:e.target.value}})}/></Field><Field label="Observaciones"><textarea value={modal.form.observations} onChange={e=>setModal({...modal,form:{...modal.form,observations:e.target.value}})}/></Field></Modal>}
  {detail&&<div className="overlay" onClick={()=>setDetail(null)}><aside className="internal-detail" onClick={e=>e.stopPropagation()}><button className="detail-close" onClick={()=>setDetail(null)}><X/></button><div className="detail-icon"><FileText size={30}/></div><span className={`doc-state ${detail.status}`}>{detail.status}</span><h2>{detail.title}</h2><p>{detail.description||"Sin descripción adicional."}</p><div className="detail-data">{[["Archivo",detail.original_file_name],["Tipo",detail.document_type],["Tamaño",fmt(detail.size_bytes)],["Carpeta",detail.folder_name||"Raíz"],["Subido por",detail.uploaded_by_name],["Fecha",detail.created_at_formatted],["Etiquetas",detail.tags||"—"],["Observaciones",detail.observations||"—"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><a className="btn btn-primary" href={`/api/internal-docs/documents/${detail.id}/file`} target="_blank"><Download size={16}/> Abrir / descargar</a><h3>Historial del documento</h3><div className="detail-events">{docEvents.map(e=><article key={e.id}><History size={14}/><p><b>{e.description}</b><span>{e.actor_name} · {e.created_at_formatted}</span></p></article>)}</div></aside></div>}
 </section>
}
function FolderTree({folders,parent,selected,onSelect,level=0}){return <div className="folder-tree">{folders.filter(f=>Number(f.parent_id||0)===Number(parent||0)).map(f=><div key={f.id}><button className={Number(selected)===Number(f.id)?"on":""} style={{paddingLeft:12+level*16}} onClick={()=>onSelect(f.id)}>{Number(f.subfolder_count)?<FolderOpen size={16}/>:<Folder size={16}/>}<span>{f.name}<small>{f.document_count} docs</small></span></button><FolderTree folders={folders} parent={f.id} selected={selected} onSelect={onSelect} level={level+1}/></div>)}</div>}
function folderLabel(f,all){const p=all.find(x=>Number(x.id)===Number(f.parent_id));return p?`${folderLabel(p,all)} / ${f.name}`:f.name}
function Destination({path}){return <div className="destination"><FolderOpen size={17}/><span>Ubicación: <b>Documentación Interna{path.map(x=>` / ${x.name}`).join("")}</b></span></div>}
function Field({label,children}){return <label className="internal-field"><span>{label}</span>{children}</label>}
function Modal({title,subtitle,children,onClose,onSave,busy,wide}){return <div className="overlay" onClick={onClose}><div className={`modal internal-modal ${wide?"wide":""}`} onClick={e=>e.stopPropagation()}><header><div><h3>{title}</h3><p>{subtitle}</p></div><button onClick={onClose}><X size={18}/></button></header><div className="modal-body">{children}</div><footer><button className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={busy} onClick={onSave}>{busy?"Guardando…":"Guardar"}</button></footer></div></div>}
