"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronRight, FileText, Folder, FolderOpen, Search } from "lucide-react";

const TIER_LABELS={estrategico:"Estratégico",misional:"Misional",apoyo:"Apoyo",evaluacion:"Evaluación"};
const STATES={vigente:"Vigente",no_publicado:"No publicado",obsoleto:"Obsoleto",anulado:"Anulado"};

export default function ProcessDetailView({process,docs=[],docTypes=[],onBack,onOpenDoc}){
  const[tab,setTab]=useState("general"),[query,setQuery]=useState(""),[open,setOpen]=useState({});
  const processDocs=docs.filter(d=>d.processId===process.id);
  const visibleDocs=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return processDocs;return processDocs.filter(d=>[d.code,d.name,d.file].filter(Boolean).some(x=>String(x).toLowerCase().includes(q)))},[processDocs,query]);
  const grouped=docTypes.map(t=>({type:t,items:visibleDocs.filter(d=>d.typeId===t.id)})).filter(g=>g.items.length);
  return <section className="section dashboard-section process-detail-view"><div className="crumb premium-crumb"><button onClick={onBack}><ArrowLeft size={15}/> Volver al mapa</button><ChevronRight size={14}/><span>{process.name}</span></div><div className="process-sheet-hero"><div className="process-logo-box"><img src="/branding/logo-grupo-ingenio.png" alt="Grupo Ingenio" onError={e=>{e.currentTarget.style.display="none"}}/></div><div className="process-sheet-main"><div className="eyebrow">Caracterización del proceso</div><h2>{process.name}</h2><p><b>Proceso:</b> {process.name}</p></div><div className="process-code-box"><b>Código</b><span>{process.sigla}</span><b>Clasificación</b><span>{TIER_LABELS[process.tier]||process.tier}</span></div></div><div className="process-tabs"><button className={tab==="general"?"on":""} onClick={()=>setTab("general")}>General</button><button className={tab==="caracterizacion"?"on":""} onClick={()=>setTab("caracterizacion")}>Caracterización</button><button className={tab==="documentacion"?"on":""} onClick={()=>setTab("documentacion")}>Documentación ({processDocs.length})</button></div>{tab!=="documentacion"?<GeneralProcess process={process} docs={processDocs}/>:<div className="process-docs-panel"><div className="searchbar" style={{maxWidth:420}}><Search size={16}/><input placeholder="Buscar documento/registro" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="doc-tree"><div className="tree-title"><FolderOpen size={18}/> Documentación</div>{grouped.map(g=>{const isOpen=open[g.type.id]!==false;return <div className="doc-folder" key={g.type.id}><button className="folder-line" onClick={()=>setOpen({...open,[g.type.id]:!isOpen})}>{isOpen?<ChevronDown size={15}/>:<ChevronRight size={15}/>}<Folder size={17}/> {g.type.name} <span>({g.items.length})</span></button>{isOpen&&<div className="folder-docs">{g.items.map(d=><button className="tree-doc" key={d.id} onClick={()=>onOpenDoc(d)}><FileText size={16}/><span className="code">{d.code}</span><strong>{d.name}</strong><em>V {d.version}</em><small>{STATES[d.state]||d.state}</small></button>)}</div>}</div>})}{!grouped.length&&<div className="empty-state"><h3>Sin documentos</h3><p>No hay documentos asociados a este proceso o al filtro actual.</p></div>}</div></div>}</section>
}

function GeneralProcess({process,docs}){return <><div className="process-badges"><div className="process-badge"><b>{process.sigla}</b><span>Código</span></div><div className="process-badge"><b>{TIER_LABELS[process.tier]||process.tier}</b><span>Clasificación</span></div><div className="process-badge"><b>{docs.length}</b><span>Documentos</span></div><div className="process-badge"><b>{docs.filter(d=>d.state==="vigente").length}</b><span>Vigentes</span></div></div><div className="process-info-card"><h3>Objetivo</h3><p>Gestionar las actividades asociadas al proceso <b>{process.name}</b>, asegurando disponibilidad documental y trazabilidad de sus registros.</p></div><div className="process-info-card"><h3>Dueño del proceso</h3><p>Responsable o líder designado para el proceso <b>{process.name}</b>.</p></div><div className="process-info-card"><h3>Alcance</h3><p>Desde la planeación y generación de documentos hasta su consulta, actualización y uso dentro de rutas de trabajo o evidencias asociadas.</p></div><div className="process-info-card"><h3>Subprocesos</h3><div className="subprocess-list"><span>Documentos asociados</span><span>Formatos</span><span>Registros</span><span>Anexos</span><span>Indicadores</span><span>Planes de mejora</span></div></div></>}
