ALTER TABLE contract_routes ADD COLUMN IF NOT EXISTS object TEXT NULL;
ALTER TABLE contract_routes ADD COLUMN IF NOT EXISTS start_date DATE NULL;
ALTER TABLE contract_routes ADD COLUMN IF NOT EXISTS end_date DATE NULL;
ALTER TABLE contract_routes ADD COLUMN IF NOT EXISTS internal_responsible_id INT NULL;
ALTER TABLE contract_routes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
CREATE TABLE IF NOT EXISTS contract_users(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,user_id INT NOT NULL,role_in_contract VARCHAR(40) NOT NULL DEFAULT 'apoyo',assigned_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_contract_user(contract_id,user_id),INDEX(contract_id),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contract_document_requests(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,name VARCHAR(220) NOT NULL,description TEXT,section VARCHAR(40) NOT NULL,required TINYINT(1) DEFAULT 1,due_date DATE,applies_to VARCHAR(20) DEFAULT 'all',assigned_user_id INT,allow_multiple TINYINT(1) DEFAULT 0,created_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(contract_id),INDEX(assigned_user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contract_document_submissions(id INT AUTO_INCREMENT PRIMARY KEY,request_id INT NOT NULL,contract_id INT NOT NULL,user_id INT NOT NULL,file_name VARCHAR(255),file_path VARCHAR(255),mime_type VARCHAR(160),size_bytes BIGINT,status VARCHAR(25) DEFAULT 'enviado',user_comment TEXT,admin_observation TEXT,reviewed_by INT,reviewed_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(request_id),INDEX(contract_id),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contract_events(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,actor_user_id INT,event_type VARCHAR(50) NOT NULL,description VARCHAR(500) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(contract_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
