export async function ensureContractSchema(pool){
  const cols=[['object','TEXT NULL'],['start_date','DATE NULL'],['end_date','DATE NULL'],['internal_responsible_id','INT NULL'],['updated_at','TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP']];
  const [existing]=await pool.query("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='contract_routes'");const names=new Set(existing.map(x=>x.COLUMN_NAME));for(const[c,t]of cols)if(!names.has(c))await pool.query(`ALTER TABLE contract_routes ADD COLUMN ${c} ${t}`);
  await pool.query(`CREATE TABLE IF NOT EXISTS contract_members(contract_id INT NOT NULL,user_id INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(contract_id,user_id),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS contract_users(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,user_id INT NOT NULL,role_in_contract VARCHAR(40) NOT NULL DEFAULT 'apoyo',assigned_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_contract_user(contract_id,user_id),INDEX(contract_id),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS contract_document_requests(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,name VARCHAR(220) NOT NULL,description TEXT,section VARCHAR(40) NOT NULL,required TINYINT(1) DEFAULT 1,due_date DATE,applies_to VARCHAR(20) DEFAULT 'all',assigned_user_id INT,allow_multiple TINYINT(1) DEFAULT 0,created_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(contract_id),INDEX(assigned_user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS contract_document_submissions(id INT AUTO_INCREMENT PRIMARY KEY,request_id INT NOT NULL,contract_id INT NOT NULL,user_id INT NOT NULL,file_name VARCHAR(255),file_path VARCHAR(255),mime_type VARCHAR(160),size_bytes BIGINT,status VARCHAR(25) DEFAULT 'enviado',user_comment TEXT,admin_observation TEXT,reviewed_by INT,reviewed_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(request_id),INDEX(contract_id),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS contract_events(id INT AUTO_INCREMENT PRIMARY KEY,contract_id INT NOT NULL,actor_user_id INT,event_type VARCHAR(50) NOT NULL,description VARCHAR(500) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(contract_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
}
export async function canAccessContract(pool,me,id){if(me?.isAdmin)return true;const [[x]]=await pool.query("SELECT 1 ok FROM contract_users WHERE contract_id=? AND user_id=? UNION SELECT 1 FROM contract_members WHERE contract_id=? AND user_id=? LIMIT 1",[id,me.id,id,me.id]);return!!x}
export async function addContractEvent(pool,id,userId,type,description){await pool.query("INSERT INTO contract_events(contract_id,actor_user_id,event_type,description) VALUES(?,?,?,?)",[id,userId,type,description])}
